name: ravencointlite
description: Ravencoint Lite Wallet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility plugins
  provider: ^5.0.0
  http: ^0.12.0+2
  #majascan: ^0.4.0
  flutter_barcode_scanner: ^1.0.2
  local_auth: 0.6.3+4
  flutter_inappwebview: ^4.0.0+4
  permission_handler: ^5.1.0+2
  csv: ^4.0.3
  file_picker: ^1.13.3
  flutter_web_browser: "^0.12.0"

  # Bitcoin plugins
  bitcoin_flutter: ^2.0.1
  bip39: ^1.0.3
  bip32: ^1.0.5
  hex: ^0.1.2
  
  # Storage plugins
  flutter_secure_storage: ^3.3.3
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  path_provider: ^1.5.1

  # UI/Component plugins
  animations: ^1.1.2
  toast: ^0.1.5
  flare_flutter: ^2.0.6
  flutter_inner_drawer: ^0.5.7+2
  flutter_echarts: ^1.3.5
  marquee: ^1.5.2
  sticky_headers: ^0.1.8
  google_fonts: ^1.0.0
  pretty_qr_code: ^1.0.1
  share: ^0.6.4
  url_launcher: ^5.5.0
  timeago: ^2.0.26
  #flutter_money_formatter: ^0.8.3
  #money_formatter: ^0.0.2
  currency_formatter: ^1.1.1
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  rounded_loading_button: ^1.0.0
  pinput: ^0.2.5
  modal_bottom_sheet: 2.0.0
  hive_generator: ^0.8.2
  flutter_hooks: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9


flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "121212"
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/rvl.png
    - assets/images/work-in-progress.png
    - assets/images/splash.png
    - assets/images/mastercard.png
    - assets/images/mastercard.jpg
    - assets/images/visa.png
    - assets/images/bank.png
    - assets/images/card.png
    - assets/images/404image.png
    - assets/images/twitter-icon.png
    - assets/images/telegram-icon.png
    - assets/rive/success.flr
    - assets/icon/icon.png
    - google_fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
